/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio1.h"
#include <stdlib.h>

void
calculadora_prog_1(char *host)
{
	CLIENT *clnt;
	operandos enteros;
	int  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	/*-------------------------------------------------
		Creamos la interfaz de dialogo para el usuario
	-------------------------------------------------*/
	int opcion = 1;
	while(opcion != 0){
		system("clear");

		printf("CALCULADORA\n\n");
		printf("Escoja una opción:\n");
		printf("1: Sumar dos enteros.\n");
		printf("2: Multiplicar dos enteros.\n");
		printf("3: Restar dos enteros.\n");
		printf("4: Dividir dos enteros.\n");
		printf("0: Salir.\n\n");
		printf("Opción: ");
		scanf("%d", &opcion);

		if (opcion != 0 && opcion < 5) {
			printf("\nIntroduzca el primer operando: ");
			scanf("%d", &enteros.a);
			printf("\nIntroduzca el segundo operando: ");
			scanf("%d", &enteros.b);
		}

		switch(opcion){
			case 1:
				result = suma_1(&enteros, clnt);
				if (result == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				break;

			case 2:
				result = multiplicacion_1(&enteros, clnt);
				if (result == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				break;
			case 3:
				result = resta_1(&enteros, clnt);
				if (result == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				break;
			case 4:
				if (enteros.b == 0) {
					printf("ERROR: no se puede dividir entre 0\n");
					*result = 0;
					break;
				}
				result = division_1(&enteros, clnt);
				if (result == (int *) NULL) {
					clnt_perror (clnt, "call failed");
				}

				break;
			case 0:
				system("clear");
				printf("\nFIN DEL PROGRAMA\n");
				break;

			default:
				printf("La opción introducida no es correcta. Presione una tecla para continuar\n");
				getchar();getchar();
		}


		if (opcion != 0 && opcion < 5) {
			printf("Resultado: %d\n", *result);
			printf("Presione una tecla para continuar\n");
			getchar();getchar();

		}
	}
	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_prog_1 (host);
exit (0);
}
