/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ejercicio3.h"
#include <time.h>


void
suma_prog_1(char *host)
{
	srand(time(NULL));
	CLIENT *clnt;
	int  *result_1;
	operandos  suma_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUMA_PROG, SUMA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	suma_1_arg.a = rand()%10;
	suma_1_arg.b = rand()%10;
	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	clock_t begin = clock();
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[1];
	for (int i = 0; i < 100000; i++) {
		suma_prog_1 (host);
	}


	clock_t end = clock();
	double tiempo_ejecucion = (double) (end-begin) / CLOCKS_PER_SEC;
	printf("TIEMPO DE EJECUCIÓN: %f\n", tiempo_ejecucion);
	exit (0);
}
